config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :todos
  root 'todos#index'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	before_filter :authenticate_user! 
	
	def index
		@todos = current_user.todos
	end

	def show
	end

	def new
		@todo = current_user.todos.build
	end

	def create
		@todo = current_user.todos.build(todo_params)
		@todo.save
		redirect_to todos_path
	end

	def edit
		@todo = find_todo
	end

	def update
		@todo = find_todo
		@todo.update_attributes(todo_params)
		redirect_to todos_path
	end

	def delete
		@todo = find_todo
	end

	def destroy
		@todo = find_todo
		@todo.destroy
		redirect_to todos_path
	end

	private

	def find_todo
		current_user.todos.find(params[:id])
	end

	def todo_params
		params.require(:todo).permit(:user_id, :item)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="row">
    <div class="small-6 large-centered columns">
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

        <%= yield %>
        <%= javascript_include_tag "application" %>
      </div>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>

	<% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>

  <div class="actions">
    <%= f.submit "Create item", class: "button" %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit item</h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<h1>To do list Index</h1>

<% @todos.each do |todo| %>
<div>
	<p>
		<%= todo.item %>
		<%= link_to "Edit", edit_todo_path(todo) %>
		<%= link_to "Delete", todo, method: :delete %>
	</p>
</div>
<% end %>
<%= link_to 'Create new item', new_todo_path %></br>
<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>

app/views/todos/new.html.erb
<h1>New to do item</h1>

<%= render 'form' %>

<%= link_to "To do index", todos_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>